#!/bin/bash
# Locks the screen with a image and shuts the screen off after 10 seconds
# Run in background
(
  sleep 10
  # If we are loggin in or logged in don't shut the screen off
  trap '' TERM
  xset dpms force off
) &
# Show image on the window
eval 'exec xloadimage -fullscreen -border black -windowid $XSCREENSAVER_WINDOW ${HOME}/.config/screensaver/screensaver.png'
