#!/bin/bash
# Locks the screen with a image that is darkend by 50% and shuts the screen off after 10 seconds
# Run in background
(
  sleep 10
  # If we are loggin in or logged in don't shut the screen off
  trap '' TERM
  xset dpms force off
) &
# Show image on the window
eval 'exec xloadimage -brighten 50 -fullscreen -border black -windowid $XSCREENSAVER_WINDOW ${HOME}/.config/screensaver/screensaver.png'
