#!/bin/bash
lastbatt="100"
batt="$(acpi | sed "s/.*\( \(.*\)%\).*/\2/g" | tr -d "\n")"
while true; do
    batt="$(acpi | sed "s/.*\( \(.*\)%\).*/\2/g" | tr -d "\n")"
    if (( $lastbatt-$batt > 9 )); then
        lastbatt=$batt
        urgency="normal"
        if [[ $batt < 20 ]]; then
            urgency="critical"
        fi
        notify-send -u $urgency "$(/home/tleilaxu/.dotfiles/scripts/battery_level_status)"
    fi
    sleep 5m
done
