#!/bin/bash
interface_name="wlp3s0"

if [ -z "$(ip link show dev $interface_name up)"  ]; then
    sudo ip link set $interface_name up
fi

comm -12 <(sudo iw dev $interface_name scan | awk '/SSID/ {print $2}' | sort) <(netctl list | sed "s/^[ |*]*//" | sort)

sudo ip link set $interface_name down
