#!/bin/sh
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify my_app_name 0 '' "$@" "" "[]" {} 10000  | sed 's/[^ ]* //; s/,.//' > /tmp/last_id
