#! /bin/bash
if acpi | grep -q "Charging"; then
    status="🔌"
elif acpi | grep -q "Discharging"; then
    status="🔌 ×"
fi
batt=$(/home/tleilaxu/.dotfiles/scripts/battery_level_status)
vol="$(/home/tleilaxu/.dotfiles/scripts/volume_status)"
notify-send "<span size='x-large'>$status</span> $batt $vol <span size='x-large'>🗓  </span>$(date +%d.%m) <span size='x-large'>🕑 </span>$(date +%R)"
