#! /bin/bash
if acpi | grep -q "Charging"; then
    status="$(echo -e '\uf1e6')"
elif acpi | grep -q "Discharging"; then
    status="$(echo -e '\uf1e6') ×"
fi
batt=$(/home/tleilaxu/.dotfiles/scripts/battery_level_status)
vol="$(/home/tleilaxu/.dotfiles/scripts/volume_status)"
echo -n "<span size='large'>$status</span>  $batt  $vol  <span size='large'>$(echo -e '\uf073')  </span>$(date +%d.%m) <span size='large'> $(echo -e '\uf017')  </span>$(date +%R)"
