#! /bin/sh
echo -en "$(curl wttr.in 2> /dev/null)" \
| sed '3,7!d' \
| sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
#(echo -en "$(curl wttr.in 2> /dev/null)" | sed '8,17!d' | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g")
